q1 = float(input("Q1. what is a number equal to 5?\n>"))
print(q1==5)
q2 = float(input("Q2. what is a number less than to 5?\n>"))
print(q2<5)
q3 = float(input("Q3. what is a number greater than to 5?\n>"))
print(q3>5)
q4 = float(input("Q4. what is a number less than or equal to 5?\n>"))
print(q4<=5)
q5 = float(input("Q5. what is a number greater than or equal to 5?\n>"))
print(q5>=5)
q6 = float(input("Q6. what is a whole number less than 5 and greater than -5?\n>"))
print(-5<q6<5)
q7 = float(input("Q7. what is a whole number less than -5 or greater than 5?\n>"))
print(q7>5 or q7<-5)
q8= float(input("Q8. what is a number that is not 5\n>"))
print(not q8==5)